apiVersion: apps/v1
kind: Deployment
metadata:
  name: r-finance-fe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: r-finance-fe
  template:
    metadata:
      labels:
        app: r-finance-fe
    spec:
      containers:
      - name: r-finance-fe
        image: your-dockerhub-username/r-finance-fe:latest
        ports:
        - containerPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: r-finance-fe
spec:
  type: NodePort
  selector:
    app: r-finance-fe
  ports:
  - protocol: TCP
    port: 80
    targetPort: 4000
    nodePort: 30001
