apiVersion: apps/v1
kind: Deployment
metadata:
  name: r-finance-fe
spec:
  replicas: 2
  selector:
    matchLabels:
      app: r-finance-fe
  template:
    metadata:
      labels:
        app: r-finance-fe
    spec:
      containers:
      - name: r-finance-fe
        image: rado23/r-finance-fe:latest
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: r-finance-fe
spec:
  type: NodePort
  selector:
    app: r-finance-fe
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30001
