name: Deploy to k3s

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets_DOCKER_USERNAME }}
        password: ${{ secrets_DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: your-dockerhub-username/my-nginx-image:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up kubectl
      uses: actions/setup-kubectl@v1
      with:
        version: 'latest'

    - name: Set up K3s kubeconfig
      run: echo "${{ secrets_KUBECONFIG }}" > $HOME/.kube/config

    - name: Deploy to k3s
      run: kubectl apply -f r-finance-fe-deployment.yaml
